import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const FavoriteStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F5F5" },

  /* ── Header ── */
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#D4A574",
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: { fontSize: 18, fontWeight: "800", color: "#1B1B1B" },
  headerCount: { fontSize: 16, fontWeight: "600", color: "#999" },
  clearBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FFF0F0",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  clearAll: { fontSize: 13, color: "#FF6B6B", fontWeight: "700" },
  headerSelect: {
    backgroundColor: "#D4A574",
    borderBottomColor: "#C49464",
  },
  closeBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(255,255,255,0.25)",
    justifyContent: "center",
    alignItems: "center",
  },
  selectActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  selectAllBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.25)",
  },
  selectAllText: { fontSize: 13, color: "#fff", fontWeight: "600" },

  /* ── List ── */
  listPad: { padding: 16, paddingBottom: 100 },
  emptyContainer: { flex: 1 },

  /* ── Swipe to Delete ── */
  swipeContainer: {
    marginBottom: 14,
    borderRadius: 16,
    overflow: "hidden",
  },
  swipeDeleteBg: {
    position: "absolute",
    top: 0,
    bottom: 0,
    right: 0,
    width: 120,
    backgroundColor: "#FF6B6B",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  swipeDeleteBtn: {
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  swipeDeleteText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },

  /* ── Card ── */
  card: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 16,
    overflow: "hidden",
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    borderWidth: 2,
    borderColor: "transparent",
  },
  cardSelected: {
    borderColor: "#D4A574",
    backgroundColor: "#FFF9F3",
  },
  checkboxOverlay: {
    position: "absolute",
    top: 8,
    left: 8,
    zIndex: 10,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#fff",
    backgroundColor: "rgba(0,0,0,0.25)",
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxActive: {
    backgroundColor: "#D4A574",
    borderColor: "#D4A574",
  },
  imageBox: {
    width: 100,
    height: 100,
    backgroundColor: "#F8F8F8",
    position: "relative",
    margin: 8,
    borderRadius: 12,
    overflow: "hidden",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  categoryTag: {
    position: "absolute",
    bottom: 6,
    left: 6,
    backgroundColor: "rgba(0,0,0,0.55)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  categoryTagText: {
    color: "#fff",
    fontSize: 9,
    fontWeight: "700",
  },
  cardBody: {
    flex: 1,
    padding: 12,
    justifyContent: "center",
  },
  brand: {
    fontSize: 11,
    color: "#999",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  name: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1B1B1B",
    marginTop: 4,
    lineHeight: 20,
  },
  cardBottom: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
    gap: 8,
  },
  price: {
    fontSize: 16,
    fontWeight: "800",
    color: "#D4A574",
  },
  discountBadge: {
    backgroundColor: "#FF6B6B",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  discountText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "800",
  },

  /* ── Empty State ── */
  empty: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 80,
    paddingHorizontal: 40,
  },
  emptyIconCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#FFF5EE",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1B1B1B",
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 28,
  },
  browseBtn: {
    backgroundColor: "#D4A574",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 36,
  },
  browseBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
  },

  /* ── Floating Action Bar ── */
  floatingBar: {
    position: "absolute",
    bottom: 16,
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#D4A574",
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 20,
    elevation: 12,
    shadowColor: "#B8895A",
    shadowOpacity: 0.3,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  floatingText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  floatingDeleteBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.25)",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
  },
  floatingDeleteText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
  },

  /* ── Custom Modal ── */
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 28,
    alignItems: "center",
    elevation: 10,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  modalIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#FFF0F0",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1B1B1B",
    marginBottom: 8,
    textAlign: "center",
  },
  modalMessage: {
    fontSize: 14,
    color: "#777",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 24,
  },
  modalBtnRow: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  modalCancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: "#F5F5F5",
    alignItems: "center",
  },
  modalCancelText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#666",
  },
  modalConfirmBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: "#FF6B6B",
    alignItems: "center",
  },
  modalConfirmText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#fff",
  },
});
